### ISSUE TITLE
Use of spdxexp as a library

### ISSUE THREAD

**Issue by spiffcs** [github/go-spdx#36]
👋 Thanks for the awesome implementation and `Satisfies` functionality.

Over in [syft](https://github.com/anchore/syft) we're trying to upgrade how we handle the complex license statements from SPDX.

I noticed that `parse.go` and `scan.go` has a lot of really good private functionality for reading these complex SPDX expressions. 

Would you all accept a PR that exposed a few methods of this package so we could incorporate the parsing logic into how we identify and parse license in our SBOM output?

**Comment by elrayle** [comment]
Absolutely.  We considered exposing some of those packages, but decided to initially start out with a small public API until a use case arose to expand it.
