### ISSUE TITLE
add unit tests for exceptions.go

### ISSUE THREAD

**Issue by khareyash05** [github/go-spdx#45]
I would like to add unit tests for `cmd/exceptions.go`

**Comment by elrayle** [comment]
That would be great.  Feel free to create a PR with the unit tests.

**Comment by khareyash05** [comment]
@elrayle Have a look!

**Comment by loginglive** [comment]
Ramsalm

**Comment by loginglive** [comment]
![FB_IMG_1684914866094](https://github.com/github/go-spdx/assets/130265523/06f672a9-4fed-49f9-8760-ccac6588e119)
